### ISSUE TITLE
Support package protected classes used in Java mappings

### ISSUE THREAD

**Issue by chirino** [redhat-ipaas/ipaas-datamapper#38]
Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
com.mediadriver.atlas.api.v2.AtlasException: Class com.mediadriver.atlas.java.module.v2.JavaModule can not access a member of class twitter4j.StatusJSONImpl with modifiers "public"
	at com.mediadriver.atlas.java.module.v2.JavaModule.processInput(JavaModule.java:80)
	at com.mediadriver.atlas.core.v2.DefaultAtlasContext.process(DefaultAtlasContext.java:146)
	at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:188)
	at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71)
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:145)
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:541)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:198)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:120)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:198)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at org.apache.camel.component.connector.ConnectorConsumerProcessor.process(ConnectorConsumerProcessor.java:66)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:97)
	at org.apache.camel.component.twitter.consumer.TwitterConsumerPolling.poll(TwitterConsumerPolling.java:64)
	at org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:174)
	at org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
09:18:41.516 [Camel (3) thread #0 - twitter://timeline/mentions] ERROR o.a.c.processor.DefaultErrorHandler - Failed delivery for (MessageId: ID-Hirams-MBP-2-home-64383-1492780715524-0-39 on ExchangeId: ID-Hirams-MBP-2-home-64383-1492780715524-0-40). Exhausted after delivery attempt: 1 caught: com.mediadriver.atlas.api.v2.AtlasException: Class com.mediadriver.atlas.java.module.v2.JavaModule can not access a member of class twitter4j.StatusJSONImpl with modifiers "public"

**Comment by mattrpav** [comment]
Copy of the mapping definition?

For a work around: try using the getter by matching case: ie.. in the mapping definition use "User" instead of "user".

**Comment by chirino** [comment]
See:

https://gist.github.com/chirino/5c4ab5e4921de99685527384b2850351

**Comment by mattrpav** [comment]
twitter4j.StatusJSONImpl is package protected. Need to set accessibility = true before.
